#!/usr/bin/env python

import sys
import json
from nap.gamefile import Player
from nap.prereg import PreReg, PairEntry, Seat

if __name__ == "__main__":
  pr = PreReg('a')
  a = Player('Belcher','R Gerry','R737847')
  b = Player('Viola','Joe','J367110')
  seat = pr.add_entry(a,b)
  flight = {
    'flight': pr.flight,
    'section': pr.get_section(),
  }
  json_flight = json.dumps(flight, sort_keys=True, indent=4, separators=(',',': '))
  print json_flight

  sys.exit(0)
