#!/usr/bin/env python

import sys
import json
from nap.gamefile import Player
from nap.prereg import PreReg, PairEntry, Seat

if __name__ == "__main__":
  pr = PreReg('a')

  a = Player('Belcher','R Gerry','R737847')
  b = Player('Viola','Joe','J367110')
  seat = pr.add_entry(a,b)

  seat = pr.add_entry(
    Player('Bass','Robert','M133560'),
    Player('Bazil','Anne','K502585'),
    req_ns=True,
  )

  seat = pr.add_entry(
    Player('Biederman','Sharon','K930102'),
    Player('Bird','Nicola','Q559120'),
    req_ns=True,
  )

  seat = pr.add_entry(
    Player('Bernstein','Bernstein','4739787'),
    Player('Blaufarb','Myrna','R178317'),
  )

  print pr.as_json()

  sys.exit(0)
