#!/usr/bin/env python

import sys
import json
from nap.gamefile import Player
from nap.prereg import PreReg, PairEntry, Seat

if __name__ == "__main__":
  data = sys.stdin.read();
  pr = PreReg()
  pr.init_from_json(data)

  print pr.as_json()

  print "\n\nMax table: %s" % pr.find_max_table()

  sys.exit(0)
