#!/usr/bin/env python

import sys
import json
from nap.gamefile import Player
from nap.prereg import PreReg, PairEntry, Seat

if __name__ == "__main__":
  data = sys.stdin.read();
  flight = json.loads(data)
  pr = PreReg(flight['flight'])
  pr.init_from_dict(flight)

  print pr.get_section()

  sys.exit(0)
