"""Object structure for ACBLscore game files

This tree of objects is extracted from a JSON dictionary generated by the
ACBLgamedump.pl perl utility by Matthew J. Kidd.

The top level object is the Gamefile, which includes helper methods for
accessing the lower-level objects and attributes.

Since this tree is oriented towards reports relevant to the North American
Pairs district-level tournament, only attributes relevant to those uses
are included in the objects.

This is NOT a general-purpose game file abstraction.
"""

from gamefile import Gamefile
from gamefile_exception import GamefileException
from club import Club
from event import Event
from event_details import EventDetails
from section import Section
from player import Player
from qualdate import QualDate
from strat import Strat
from reference import GFUtils

